apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: ceph-filesystem
---
apiVersion: v1
kind: Pod
metadata:
  name: fio-test
spec:
  volumes:
    # Use the Ceph FS that we have provisioned
    - name: test-storage
      persistentVolumeClaim:
        claimName: cephfs-pvc
        readOnly: false
  containers:
    - name: fio-test
      image: joshio94/dos:latest
      # Mount our volume to /data inside the container
      volumeMounts:
        - mountPath: "/data"
          name: test-storage
  restartPolicy: Never