apiVersion: apps/v1
kind: Deployment
metadata:
  name: fio-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fio-test-app
  template:
    metadata:
      labels:
        app: fio-test-app
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: fio-test-app
      containers:
      - name: fio-test
        image: joshio94/dos:latest
        # Mount our volume to /data inside the container
        volumeMounts:
          - mountPath: "/data"
            name: test-storage
      volumes:
        - name: test-storage
          hostPath:
            path: /mnt/drive
  